using Aevatar.Studio.Application.Studio.Contracts;

namespace Aevatar.Studio.Application.Studio.Abstractions;

/// <summary>
/// Write-side port for the StudioMember authority. Dispatches commands to
/// the per-member StudioMemberGAgent actor; never reads downstream state
/// (queries flow through <see cref="IStudioMemberQueryPort"/>).
/// </summary>
public interface IStudioMemberCommandPort
{
    /// <summary>
    /// Creates a new member under the given scope and returns the resulting
    /// summary. <paramref name="scopeId"/> and the request's
    /// <c>ImplementationKind</c> are required; <c>publishedServiceId</c> is
    /// generated by this call from the immutable member id and persisted on
    /// the actor state.
    /// </summary>
    Task<StudioMemberSummaryResponse> CreateAsync(
        string scopeId,
        CreateStudioMemberRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Updates the implementation reference for an existing member (e.g. once
    /// Studio has produced a workflow yaml, script revision, or wired up a
    /// gagent type for the member). Idempotent on identical inputs.
    /// </summary>
    Task UpdateImplementationAsync(
        string scopeId,
        string memberId,
        StudioMemberImplementationRefResponse implementation,
        CancellationToken ct = default);

    /// <summary>
    /// Records that an already-published member service now points at a new
    /// implementation revision without creating a binding run.
    /// </summary>
    Task RecordPublishedBindingAsync(
        string scopeId,
        string memberId,
        StudioMemberPublishedBindingRecordRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Renames an existing member through the member actor's authoritative
    /// rename event. Identity fields and implementation references are left
    /// unchanged by the actor state transition.
    /// </summary>
    Task RenameAsync(
        string scopeId,
        string memberId,
        string displayName,
        CancellationToken ct = default);

    /// <summary>
    /// Starts an asynchronous binding run. Implementations dispatch a
    /// <c>StudioMemberBindingRunRequested</c> message to a run actor and
    /// return after the message is accepted for dispatch; they do not wait
    /// for member admission, platform binding, or read-model visibility.
    /// </summary>
    Task StartBindingRunAsync(
        StudioMemberBindingRunStartRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Dispatches the caller's PATCH team-assignment intent to the
    /// StudioMember actor. <paramref name="targetTeamId"/> null means explicit
    /// unassign; a non-empty value means assign / move. The member actor owns
    /// the current-team lookup, no-op decision, and committed reassignment
    /// event construction.
    /// </summary>
    // Refactor (iter96/cluster-545):
    //   Old pattern: ReassignTeamAsync(fromTeamId, toTeamId) — application service constructed reassignment event with both team ids
    //   New principle: PatchTeamAssignmentAsync(targetTeamId) — forwards PATCH intent to StudioMemberGAgent which evaluates current vs target from authoritative actor state
    Task PatchTeamAssignmentAsync(
        string scopeId,
        string memberId,
        string? targetTeamId,
        CancellationToken ct = default);

    /// <summary>
    /// Dispatches a tombstone command to the StudioMember actor. The actor
    /// owns idempotency and emits any required team-removal fact before the
    /// delete event; published service artifacts remain owned by the platform
    /// service lifecycle and are not cleaned up here.
    /// </summary>
    Task DeleteAsync(
        string scopeId,
        string memberId,
        CancellationToken ct = default);
}
