using Aevatar.Studio.Application.Studio.Contracts;

namespace Aevatar.Studio.Application.Studio.Abstractions;

/// <summary>
/// Write-side port for the StudioMember authority. Dispatches commands to
/// the per-member StudioMemberGAgent actor; never reads downstream state
/// (queries flow through <see cref="IStudioMemberQueryPort"/>).
/// </summary>
public interface IStudioMemberCommandPort
{
    /// <summary>
    /// Creates a new member under the given scope and returns the resulting
    /// summary. <paramref name="scopeId"/> and the request's
    /// <c>ImplementationKind</c> are required; <c>publishedServiceId</c> is
    /// generated by this call from the immutable member id and persisted on
    /// the actor state.
    /// </summary>
    Task<StudioMemberSummaryResponse> CreateAsync(
        string scopeId,
        CreateStudioMemberRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Requests an async member binding run on an existing StudioMember
    /// authority. This command must not create a missing member actor; Create
    /// is the only command that establishes member identity.
    /// </summary>
    Task<StudioMemberBindingAcceptedResponse> RequestBindingAsync(
        string scopeId,
        string memberId,
        UpdateStudioMemberBindingRequest request,
        CancellationToken ct = default);

    /// <summary>
    /// Updates the implementation reference for an existing member (e.g. once
    /// Studio has produced a workflow yaml, script revision, or wired up a
    /// gagent type for the member). Idempotent on identical inputs.
    /// </summary>
    Task UpdateImplementationAsync(
        string scopeId,
        string memberId,
        StudioMemberImplementationRefResponse implementation,
        CancellationToken ct = default);

    /// <summary>
    /// Records that the member has been bound to its published service at the
    /// given revision. Called by the member binding orchestrator after the
    /// underlying scope binding upsert succeeds.
    /// </summary>
    Task RecordBindingAsync(
        string scopeId,
        string memberId,
        string publishedServiceId,
        string revisionId,
        string implementationKindName,
        CancellationToken ct = default);

    Task CompleteBindingAsync(
        string scopeId,
        string memberId,
        StudioMemberBindingCompletionRequest request,
        CancellationToken ct = default);

    Task FailBindingAsync(
        string scopeId,
        string memberId,
        StudioMemberBindingFailureRequest request,
        CancellationToken ct = default);
}
