#!/usr/bin/env bash
# tools/docs/build-index.sh — Generate docs/README.md from canonical docs frontmatter
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DOCS_DIR="$REPO_ROOT/docs"
OUTPUT="$DOCS_DIR/README.md"

extract_field() {
  local file="$1" field="$2"
  sed -n '2,/^---$/p' "$file" | grep "^${field}:" | sed "s/^${field}: *//" | sed 's/^"//' | sed 's/"$//'
}

{
  echo "# Aevatar Documentation"
  echo ""
  echo "> Auto-generated by \`tools/docs/build-index.sh\`. Do not edit manually."
  echo ""

  # Canonical docs
  echo "## Canonical References"
  echo ""
  echo "Authoritative architecture and developer guides. Each covers one topic."
  echo ""
  if [ -d "$DOCS_DIR/canon" ]; then
    for file in "$DOCS_DIR"/canon/*.md; do
      [ -f "$file" ] || continue
      basename=$(basename "$file")
      title=$(extract_field "$file" "title")
      [ -z "$title" ] && title="$basename"
      echo "- [${title}](canon/${basename})"
    done
  else
    echo "_No canonical docs yet._"
  fi

  echo ""

  # Decision records
  echo "## Architecture Decisions"
  echo ""
  echo "Immutable records of architectural choices and their rationale."
  echo ""
  if [ -d "$DOCS_DIR/decisions" ]; then
    for file in "$DOCS_DIR"/decisions/*.md; do
      [ -f "$file" ] || continue
      basename=$(basename "$file")
      title=$(extract_field "$file" "title")
      [ -z "$title" ] && title="$basename"
      echo "- [${title}](decisions/${basename})"
    done
  else
    echo "_No decision records yet._"
  fi

  echo ""

  # History
  echo "## History"
  echo ""
  echo "Point-in-time design snapshots. Not authoritative — for context only."
  echo ""
  if [ -d "$DOCS_DIR/history" ]; then
    for dir in "$DOCS_DIR"/history/*/; do
      [ -d "$dir" ] || continue
      month=$(basename "$dir")
      echo "### $month"
      echo ""
      for file in "$dir"*.md; do
        [ -f "$file" ] || continue
        basename=$(basename "$file" .md)
        # Use filename as title for history (no frontmatter required)
        echo "- [${basename}](history/${month}/$(basename "$file"))"
      done
      echo ""
    done
  fi

  # Audit scorecard
  if [ -d "$DOCS_DIR/audit-scorecard" ]; then
    echo "## Audit Scorecard"
    echo ""
    for file in "$DOCS_DIR"/audit-scorecard/*.md; do
      [ -f "$file" ] || continue
      basename=$(basename "$file")
      echo "- [${basename}](audit-scorecard/${basename})"
    done
    echo ""
  fi

  # Templates
  if [ -d "$DOCS_DIR/templates" ]; then
    echo "## Templates"
    echo ""
    for file in "$DOCS_DIR"/templates/*.md; do
      [ -f "$file" ] || continue
      basename=$(basename "$file")
      echo "- [${basename}](templates/${basename})"
    done
    echo ""
  fi

} > "$OUTPUT"

echo "Generated $OUTPUT ($(wc -l < "$OUTPUT" | tr -d ' ') lines)"
