using System.ComponentModel;
using System.Text.Json;
using Aevatar.AI.Abstractions.ToolProviders;
using FluentAssertions;

namespace Aevatar.AI.Tests;

public class AgentToolBaseTests
{
    // ─── Test parameter type ───

    private class SearchParams
    {
        [Description("The search query")]
        public string Query { get; set; } = "";

        public int MaxResults { get; set; } = 10;
    }

    // ─── Test tool implementation ───

    private class TestSearchTool : AgentToolBase<SearchParams>
    {
        public override string Name => "test_search";
        public override string Description => "A test search tool";
        public override bool IsReadOnly => true;

        public SearchParams? LastParams { get; private set; }

        protected override Task<string> ExecuteAsync(SearchParams parameters, CancellationToken ct)
        {
            LastParams = parameters;
            return Task.FromResult($$"""{"results":[],"query":"{{parameters.Query}}","max":{{parameters.MaxResults}}}""");
        }
    }

    private class FailingTool : AgentToolBase<SearchParams>
    {
        public override string Name => "failing_tool";
        public override string Description => "A tool that throws";

        protected override Task<string> ExecuteAsync(SearchParams parameters, CancellationToken ct) =>
            throw new InvalidOperationException("boom");
    }

    // ─── ParametersSchema tests ───

    [Fact]
    public void ParametersSchema_AutoGeneratedFromType()
    {
        var tool = new TestSearchTool();

        tool.ParametersSchema.Should().NotBeNullOrWhiteSpace();

        var doc = JsonDocument.Parse(tool.ParametersSchema);
        var root = doc.RootElement;

        root.GetProperty("type").GetString().Should().Be("object");
        var props = root.GetProperty("properties");
        props.TryGetProperty("query", out _).Should().BeTrue("snake_case naming applied");
        props.TryGetProperty("max_results", out _).Should().BeTrue("snake_case naming applied");
    }

    [Fact]
    public void ParametersSchema_IsCachedAcrossInstances()
    {
        var tool1 = new TestSearchTool();
        var tool2 = new TestSearchTool();

        // Same string reference (static cached)
        ReferenceEquals(tool1.ParametersSchema, tool2.ParametersSchema).Should().BeTrue();
    }

    // ─── ExecuteAsync deserialization tests ───

    [Fact]
    public async Task ExecuteAsync_ValidJson_DeserializesAndExecutes()
    {
        var tool = new TestSearchTool();
        var result = await tool.ExecuteAsync("""{"query":"hello","max_results":5}""");

        result.Should().Contain("hello");
        tool.LastParams.Should().NotBeNull();
        tool.LastParams!.Query.Should().Be("hello");
        tool.LastParams.MaxResults.Should().Be(5);
    }

    [Fact]
    public async Task ExecuteAsync_CaseInsensitive_Deserializes()
    {
        // PropertyNameCaseInsensitive handles case variations of the snake_case names
        var tool = new TestSearchTool();
        var result = await tool.ExecuteAsync("""{"QUERY":"test","MAX_RESULTS":3}""");

        tool.LastParams.Should().NotBeNull();
        tool.LastParams!.Query.Should().Be("test");
        tool.LastParams.MaxResults.Should().Be(3);
    }

    [Fact]
    public async Task ExecuteAsync_InvalidJson_ReturnsError()
    {
        var tool = new TestSearchTool();
        var result = await tool.ExecuteAsync("not valid json");

        result.Should().Contain("error").And.Contain("Invalid parameters");
    }

    [Fact]
    public async Task ExecuteAsync_EmptyString_ReturnsError()
    {
        var tool = new TestSearchTool();
        var result = await tool.ExecuteAsync("");

        result.Should().Contain("error").And.Contain("Parameters are required");
    }

    [Fact]
    public async Task ExecuteAsync_NullString_ReturnsError()
    {
        var tool = new TestSearchTool();
        var result = await ((IAgentTool)tool).ExecuteAsync(null!);

        result.Should().Contain("error").And.Contain("Parameters are required");
    }

    // ─── IAgentTool contract tests ───

    [Fact]
    public void Implements_IAgentTool_Contract()
    {
        IAgentTool tool = new TestSearchTool();

        tool.Name.Should().Be("test_search");
        tool.Description.Should().Be("A test search tool");
        tool.ParametersSchema.Should().NotBeNullOrWhiteSpace();
        tool.IsReadOnly.Should().BeTrue();
        tool.IsDestructive.Should().BeFalse();
        tool.ApprovalMode.Should().Be(ToolApprovalMode.NeverRequire);
        tool.RequiresApproval("{}").Should().BeNull();
    }
}
