// Retained route definitions for the preserved console pages.
// These routes are deliberately NOT registered by config/routes.ts.
export const legacyConsoleRoutes = [
  {
    path: '/chat',
    name: 'Chat',
    component: './chat',
    menuGroupKey: 'chat',
    hideInMenu: false,
  },
  {
    path: '/scopes',
    component: './scopes',
    hideInMenu: true,
  },
  {
    path: '/scopes/:scopeId/teams/new',
    name: 'Create Team',
    component: './teams/new',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams',
    name: 'My Teams',
    component: './teams',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/members/new/workflow',
    name: 'Team Member Workflow Studio',
    component: './team-member-workflow-studio',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/members/:memberId/workflow',
    name: 'Team Member Workflow Studio',
    component: './team-member-workflow-studio',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/members/:memberId/invoke',
    name: 'Team Member Invoke',
    component: './team-member-invoke',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/members/:memberId/runs',
    name: 'Team Member Published Runs',
    component: './runtime-published-runs',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/members/:memberId/automations',
    component: './teams/detail',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId/work-orders/:workOrderId',
    name: 'WorkOrder Details',
    component: './team-work-order-detail',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/:scopeId/teams/:teamId',
    name: 'Team Details',
    component: './teams/detail',
    hideInMenu: true,
    parentKeys: ['/scopes'],
  },
  {
    path: '/scopes/assets',
    component: './scopes/assets',
    hideInMenu: true,
  },
  {
    path: '/scopes/files',
    name: 'Files',
    component: './scopes/files',
    menuGroupKey: 'build',
  },
  {
    path: '/studio',
    component: './studio',
    hideInMenu: true,
  },
  {
    path: '/runtime/workflows',
    component: './workflows',
    hideInMenu: true,
  },
  {
    path: '/runtime/primitives',
    name: 'Connectors',
    component: './primitives',
    hideInMenu: true,
  },
  {
    path: '/scopes/invoke',
    component: './scopes/invoke',
    hideInMenu: true,
  },
  {
    path: '/runtime/runs',
    name: 'Event Stream',
    component: './runs',
    menuGroupKey: 'platform',
  },
  {
    path: '/runtime/mission-control',
    name: 'Mission Control',
    component: './MissionControl',
    hideInMenu: true,
  },
  {
    path: '/runtime/mission-wall',
    component: './MissionWall',
    hideInMenu: true,
  },
  {
    path: '/services',
    name: 'Services',
    component: './services',
    menuGroupKey: 'platform',
  },
  {
    path: '/services/:serviceId',
    component: './services',
    hideInMenu: true,
    parentKeys: ['/services'],
  },
  {
    path: '/governance',
    name: 'Governance',
    component: './governance',
    menuGroupKey: 'platform',
  },
  {
    path: '/governance/policies',
    component: './governance/policies',
    hideInMenu: true,
    parentKeys: ['/governance'],
  },
  {
    path: '/governance/bindings',
    component: './governance/bindings',
    hideInMenu: true,
    parentKeys: ['/governance'],
  },
  {
    path: '/governance/endpoints',
    component: './governance/endpoints',
    hideInMenu: true,
    parentKeys: ['/governance'],
  },
  {
    path: '/governance/activation',
    component: './governance/activation',
    hideInMenu: true,
    parentKeys: ['/governance'],
  },
  {
    path: '/deployments',
    name: 'Deployments',
    component: './Deployments',
    menuGroupKey: 'platform',
  },
  {
    path: '/runtime/explorer',
    name: 'Topology',
    component: './actors',
    menuGroupKey: 'platform',
  },
  {
    path: '/runtime/explorer/detail',
    component: './actors/detail',
    hideInMenu: true,
    parentKeys: ['/runtime/explorer'],
  },
  {
    path: '/runtime/gagents',
    name: 'Members',
    component: './gagents',
    hideInMenu: true,
  },
  {
    path: '/scopes/overview',
    component: './scopes/overview',
    hideInMenu: true,
  },
  {
    path: '/settings',
    name: 'Settings',
    component: './settings',
    menuGroupKey: 'settings',
  },
  {
    path: '/scopes/workflows',
    redirect: '/runtime/workflows',
    hideInMenu: true,
  },
  {
    path: '/scopes/scripts',
    redirect: '/studio?tab=scripts',
    hideInMenu: true,
  },
  {
    path: '/governance/audit',
    redirect: '/governance?view=changes',
    hideInMenu: true,
  },
  {
    path: '/primitives',
    redirect: '/runtime/primitives',
    hideInMenu: true,
  },
  {
    path: '/runs',
    redirect: '/runtime/runs',
    hideInMenu: true,
  },
  {
    path: '/actors',
    redirect: '/runtime/explorer',
    hideInMenu: true,
  },
  {
    path: '/gagents',
    redirect: '/runtime/gagents',
    hideInMenu: true,
  },
  {
    path: '/mission-control',
    redirect: '/runtime/mission-control',
    hideInMenu: true,
  },
  {
    path: '/mission-wall',
    redirect: '/runtime/mission-wall',
    hideInMenu: true,
  },
];
