return {
  { module = "autonomy_result", key = "autonomy-result" },
  { module = "converge_round", key = "converge-round" },
  { module = "decomposed", key = "decomposed" },
  { module = "dependency_cycle", key = "dependency-cycle" },
  { module = "dependency_release", key = "dependency-release" },
  { module = "dependency_unresolvable", key = "dependency-unresolvable" },
  { module = "dependency_void", key = "dependency-void" },
  { module = "dependency_wait", key = "dependency-wait" },
  { module = "dependency_waiver", key = "dependency-waiver" },
  { module = "impl_failure", key = "impl-failure" },
  { module = "implement_attempt", key = "implement-attempt" },
  { module = "implementing", key = "implementing" },
  { module = "merged", key = "merged" },
  { module = "pr_delegation", key = "pr-delegation" },
  { module = "pr_link", key = "pr-link" },
  { module = "state", key = "state" },
}
