#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

line_threshold="${COVERAGE_LINE_THRESHOLD:-85}"
branch_threshold="${COVERAGE_BRANCH_THRESHOLD:-72}"
# Scope the quality gate to core production libraries. Demo apps, CLI/tooling shells,
# generated provider shells, and boundary SDK/UI adapters are validated by dedicated
# integration or consumer tests and would otherwise drown the core branch signal.
assembly_filters="${COVERAGE_ASSEMBLY_FILTERS:-+Aevatar.*;-*.Tests;-AutoGeneratedProgram;-Aevatar.Demos.*;-Aevatar.Tools.*;-Aevatar.Bootstrap;-Aevatar.*.Providers.*;-Aevatar.AI.LLMProviders.*;-Aevatar.AI.ToolProviders.*;-Aevatar.Foundation.Runtime.Persistence.Implementations.Garnet;-Aevatar.Foundation.Runtime.Streaming.Implementations.MassTransit;-Aevatar.Foundation.Runtime.Implementations.Orleans.Transport.MassTransit;-Aevatar.Workflow.Sdk;-Aevatar.Workflow.Extensions.Bridge;-Aevatar.Workflow.Presentation.AGUIAdapter}"
# Exclude all generated sources under obj/ (protobuf, source generators, etc.).
# Also exclude common generated filename patterns.
# Override via COVERAGE_GENERATED_FILE_FILTERS when needed.
generated_file_filters="${COVERAGE_GENERATED_FILE_FILTERS:--*/obj/*;-*\\obj\\*;-*Generated/*;-*.g.cs;-*.g.i.cs;-*.generated.cs;-*.Generated.cs;-*AssemblyInfo.cs;-*AssemblyAttributes.cs}"

timestamp="$(date +%Y%m%d-%H%M%S)"
output_root="artifacts/coverage/${timestamp}-ci-gate"
raw_dir="${output_root}/raw"
report_dir="${output_root}/report"

mkdir -p "${raw_dir}" "${report_dir}"

echo "Running coverage collection for production assemblies..."
dotnet test aevatar.slnx \
  --nologo \
  --no-build \
  --tl:off \
  -m:1 \
  -p:UseSharedCompilation=false \
  -p:NuGetAudit=false \
  --collect:"XPlat Code Coverage" \
  --results-directory "${raw_dir}"

echo "Restoring local tools..."
dotnet tool restore --tool-manifest .config/dotnet-tools.json

echo "Generating filtered coverage report..."
dotnet tool run reportgenerator \
  "-reports:${raw_dir}/**/coverage.cobertura.xml" \
  "-targetdir:${report_dir}" \
  "-reporttypes:JsonSummary;TextSummary" \
  "-assemblyfilters:${assembly_filters}" \
  "-filefilters:${generated_file_filters}"

summary_json="${report_dir}/Summary.json"
summary_txt="${report_dir}/Summary.txt"

line_coverage="$(jq -r '.summary.linecoverage // 0' "${summary_json}")"
branch_coverage="$(jq -r '.summary.branchcoverage // 0' "${summary_json}")"

echo "Coverage summary (filtered): line=${line_coverage}% branch=${branch_coverage}%"
echo "Coverage report path: ${summary_txt}"

line_ok="$(awk -v actual="${line_coverage}" -v threshold="${line_threshold}" 'BEGIN { if ((actual + 0) >= (threshold + 0)) print 1; else print 0; }')"
branch_ok="$(awk -v actual="${branch_coverage}" -v threshold="${branch_threshold}" 'BEGIN { if ((actual + 0) >= (threshold + 0)) print 1; else print 0; }')"

if [[ "${line_ok}" != "1" || "${branch_ok}" != "1" ]]; then
  echo "Coverage guard failed."
  echo "Required: line >= ${line_threshold}%, branch >= ${branch_threshold}%"
  echo "Actual  : line = ${line_coverage}%, branch = ${branch_coverage}%"
  exit 1
fi

echo "Coverage guard passed."
